namespace MgaSonicAnvil.Domain;

internal static partial class UiStrings
{
    public static string ColorDevTitle => Get("色調整（開発者）", "Color tuning (developer)");
    public static string ColorDevClose => Get("閉じる", "Close");
    public static string ColorDevResetToDefaults => Get("既定に戻す", "Reset to defaults");

    public static string ColorLabel(string key)
    {
        var token = key.EndsWith("Brush", StringComparison.Ordinal) ? key[..^5] : key;
        return token switch
        {
            "PrimaryFore" => Get("共通・標準文字", "Shared · standard text"),
            "MutedFore" => Get("共通・弱い文字", "Shared · muted text"),
            "AccentCyan" => Get("共通・シアンアクセント", "Shared · cyan accent"),
            "DirtyAccent" => Get("共通・未保存アクセント", "Shared · dirty accent"),
            "SurfaceBack" => Get("共通・基本背景", "Shared · base background"),
            "WindowBack" => Get("ダイアログ・背景", "Dialog · background"),
            "ChromeBack" => Get("共通・クローム背景", "Shared · chrome background"),
            "ChromeBorder" => Get("共通・クローム境界", "Shared · chrome border"),
            "ChromeMid" => Get("共通・中間グレー", "Shared · mid gray"),
            "ChromeDim" => Get("共通・無効／薄いグレー", "Shared · disabled / dim gray"),
            "ControlHoverBorder" => Get("コントロール・ホバー境界", "Control · hover border"),
            "DialogInputBack" => Get("入力欄・背景", "Input · background"),
            "MenuSeparator" => Get("メニュー・区切り", "Menu · separator"),
            "WaveformBack" => Get("波形エリア背景", "Waveform area background"),
            "WaveFill" => Get("波形", "Waveform"),
            "WaveFillOverlay" => Get("波形（スペクトログラム重ね）", "Waveform (spectrogram overlay)"),
            "WaveZeroLine" => Get("波形 0dB 線", "Waveform 0 dB line"),
            "WaveformScrollTrack" => Get("波形スクロール・トラック", "Waveform scroll · track"),
            "TimelineWellBack" => Get("タイムライン井戸・背景", "Timeline well · background"),
            "Playhead" => Get("再生ヘッド", "Playhead"),
            "SeekExit" => Get("Exit 二重再生ヘッド", "Exit dual playhead"),
            "MouseGuide" => Get("マウスガイド", "Mouse guide"),
            "MouseGuideOnSelection" => Get("マウスガイド（選択上）", "Mouse guide (on selection)"),
            "LoopRangeFill" => Get("選択範囲・塗り", "Selection · fill"),
            "SampleLoopTimeline" => Get("サンプルループ・タイムライン", "Sample loop · timeline"),
            "SampleLoopWaveFill" => Get("サンプルループ・波形塗り", "Sample loop · wave fill"),
            "SampleLoopTimeLabelFore" => Get("サンプルループ・時刻文字", "Sample loop · time text"),
            "RegionTimeline" => Get("リージョン・タイムライン", "Region · timeline"),
            "RegionWaveFill" => Get("リージョン・波形塗り", "Region · wave fill"),
            "RegionTimeLabelFore" => Get("リージョン・時刻文字", "Region · time text"),
            "Marker" => Get("マーカー", "Marker"),
            "MarkerSelected" => Get("マーカー・選択", "Marker · selected"),
            "MarkerSelectedBorder" => Get("マーカー・選択枠", "Marker · selected border"),
            "MarkerLabelFore" => Get("マーカー番号文字", "Marker number text"),
            "RegionWaveFillAnacrusis" => Get("波形リージョン（-A）", "Wave region (-A)"),
            "RegionWaveFillLoop" => Get("波形リージョン（-L）", "Wave region (-L)"),
            "RegionWaveFillExit" => Get("波形リージョン（-E）", "Wave region (-E)"),
            "RegionWaveFillExcluded" => Get("波形リージョン（-R）", "Wave region (-R)"),
            "VectorScopeBack" => Get("ベクタースコープ・背景", "Vector scope · background"),
            "VectorScopeTrace" => Get("ベクタースコープ・軌跡", "Vector scope · trace"),
            "VectorScopeGrid" => Get("ベクタースコープ・十字", "Vector scope · cross"),
            "VectorScopeCorrelation" => Get("ベクタースコープ・相関針", "Vector scope · correlation"),
            "ProjectBarBack" => Get("全体波形バー・背景", "Overview bar · background"),
            "TransportBack" => Get("トランスポート・背景", "Transport · background"),
            "TransportFore" => Get("トランスポート・文字", "Transport · text"),
            "TransportDisabledFore" => Get("トランスポート・無効文字", "Transport · disabled text"),
            "TransportHoverBack" => Get("トランスポート・ホバー", "Transport · hover"),
            "TransportPressedBack" => Get("トランスポート・押下", "Transport · pressed"),
            "WaapiToggleOffBack" => Get("WAAPI トグル・オフ背景", "WAAPI toggle · off background"),
            "WaapiToggleOffHoverBack" => Get("WAAPI トグル・オフホバー", "WAAPI toggle · off hover"),
            "WaapiToggleOffFore" => Get("WAAPI トグル・オフ文字", "WAAPI toggle · off text"),
            "WaapiToggleOnBack" => Get("WAAPI トグル・オン背景", "WAAPI toggle · on background"),
            "WaapiToggleOnHoverBack" => Get("WAAPI トグル・オンホバー", "WAAPI toggle · on hover"),
            "WaapiToggleOnFore" => Get("WAAPI トグル・オン文字", "WAAPI toggle · on text"),
            "ActionCopyrightFore" => Get("アクションバー・著作権文字", "Action bar · copyright text"),
            "ActionLinkFore" => Get("アクションバー・リンク", "Action bar · link"),
            "StatusBarBack" => Get("ステータスバー・背景", "Status bar · background"),
            "WaapiBarBack" => Get("WAAPI バー・背景", "WAAPI bar · background"),
            "StatusBarTitleFore" => Get("ステータスバー・見出し", "Status bar · heading"),
            "StatusBarDetailFore" => Get("ステータスバー・詳細文字", "Status bar · detail text"),
            "StatusBarErrorDetailFore" => Get("ステータスバー・エラー文字", "Status bar · error text"),
            "StatusBarConnectedBadgeBack" => Get("ステータスバー・CONNECT", "Status bar · CONNECT"),
            "StatusBarDisconnectedBadgeBack" => Get("ステータスバー・DISCONNECT", "Status bar · DISCONNECT"),
            "KeepTargetLockFore" => Get("Keep Target・施錠", "Keep Target · locked"),
            "KeepTargetLockHoverFore" => Get("Keep Target・施錠ホバー", "Keep Target · locked hover"),
            "KeepTargetUnlockFore" => Get("Keep Target・開錠", "Keep Target · unlocked"),
            "KeepTargetUnlockHoverFore" => Get("Keep Target・開錠ホバー", "Keep Target · unlocked hover"),
            "StatusExportButtonFill" => Get("ステータスバー・EXPORT塗り", "Status bar · EXPORT fill"),
            "StatusExportButtonHoverFill" => Get("ステータスバー・EXPORTホバー塗り", "Status bar · EXPORT hover fill"),
            "StatusExportButtonBack" => Get("ステータスバー・EXPORT枠", "Status bar · EXPORT border"),
            "StatusExportButtonHoverBack" => Get("ステータスバー・EXPORTホバー枠", "Status bar · EXPORT hover border"),
            "StatusExportButtonPressedBack" => Get("ステータスバー・EXPORT押下枠", "Status bar · EXPORT pressed border"),
            "StatusExportButtonFore" => Get("ステータスバー・EXPORT文字", "Status bar · EXPORT text"),
            "ColorPanelBack" => Get("色パネル・背景", "Color panel · background"),
            "ColorPanelListBack" => Get("色パネル・リスト背景", "Color panel · list background"),
            "ColorPanelInputBack" => Get("色パネル・入力背景", "Color panel · input background"),
            "ExportButtonFill" => Get("ダイアログ・OK塗り", "Dialog · OK fill"),
            "ExportButtonHoverFill" => Get("ダイアログ・OKホバー塗り", "Dialog · OK hover fill"),
            "ExportButtonBack" => Get("ダイアログ・OK枠", "Dialog · OK border"),
            "ExportButtonHoverBack" => Get("ダイアログ・OKホバー枠", "Dialog · OK hover border"),
            "ExportButtonPressedBack" => Get("ダイアログ・OK押下枠", "Dialog · OK pressed border"),
            "ExportButtonFore" => Get("ダイアログ・OK文字", "Dialog · OK text"),
            "ClearButtonFill" => Get("ダイアログ・キャンセル塗り", "Dialog · Cancel fill"),
            "ClearButtonHoverFill" => Get("ダイアログ・キャンセルホバー塗り", "Dialog · Cancel hover fill"),
            "ClearButtonBack" => Get("ダイアログ・キャンセル枠", "Dialog · Cancel border"),
            "ClearButtonHoverBack" => Get("ダイアログ・キャンセルホバー枠", "Dialog · Cancel hover border"),
            "ClearButtonPressedBack" => Get("ダイアログ・キャンセル押下枠", "Dialog · Cancel pressed border"),
            "ClearButtonFore" => Get("ダイアログ・キャンセル文字", "Dialog · Cancel text"),
            _ => token,
        };
    }
}
